# Generated by Django 3.1.7 on 2021-04-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0002_auto_20210428_1350'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('discount', models.BooleanField(default=False)),
                ('discount_sum', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Completed'), (2, 'Canceled')], default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
